### ISSUE TITLE
Could not create connection to database server

### ISSUE THREAD

**Issue by faker1112** [leijinjun/sms-bomb#4]
![微信截图_20230905133408](https://github.com/leijinjun/sms-bomb/assets/48475006/1e41f7b2-199b-4f86-bc5e-61b5f4ab5104)

**Comment by leijinjun** [comment]
你的数据库连接配置的是啥

**Comment by faker1112** [comment]
代码都是你的 没有改  还是你的配置

**Comment by leijinjun** [comment]
数据库配置肯定要改啊，要用你自己的啊发自我的手机-------- 原始邮件 --------发件人： 大魔王啊 ***@***.***>日期： 2023年9月6日周三 10:07收件人： leijinjun/sms-bomb ***@***.***>抄送： 冰与火丶挣扎 ***@***.***>, Comment ***@***.***>主    题： Re: [leijinjun/sms-bomb] Could not create connection to database server (Issue #4)
代码都是你的 没有改  还是你的配置

**Comment by faker1112** [comment]
> 数据库配置肯定要改啊，要用你自己的啊发自我的手机-------- 原始邮件 --------发件人： 大魔王啊 ***@***.***>日期： 2023年9月6日周三 10:07收件人： leijinjun/sms-bomb ***@***.***>抄送： 冰与火丶挣扎 ***@***.***>, Comment ***@***.***>主 题： Re: [leijinjun/sms-bomb] Could not create connection to database server (Issue #4) 代码都是你的 没有改 还是你的配置 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
不需要建表吗

**Comment by leijinjun** [comment]
工程里有建表语句发自我的手机-------- 原始邮件 --------发件人： 大魔王啊 ***@***.***>日期： 2023年9月6日周三 15:42收件人： leijinjun/sms-bomb ***@***.***>抄送： 冰与火丶挣扎 ***@***.***>, Comment ***@***.***>主    题： Re: [leijinjun/sms-bomb] Could not create connection to database server (Issue #4)

数据库配置肯定要改啊，要用你自己的啊发自我的手机-------- 原始邮件 --------发件人： 大魔王啊 @.>日期： 2023年9月6日周三 10:07收件人： leijinjun/sms-bomb @.>抄送： 冰与火丶挣扎 @.>, Comment @.>主 题： Re: [leijinjun/sms-bomb] Could not create connection to database server (Issue #4) 代码都是你的 没有改 还是你的配置 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.***>
不需要建表吗

**Comment by faker1112** [comment]
> 工程里有建表语句发自我的手机-------- 原始邮件 --------发件人： 大魔王啊 ***@***.***>日期： 2023年9月6日周三 15:42收件人： leijinjun/sms-bomb ***@***.***>抄送： 冰与火丶挣扎 ***@***.***>, Comment ***@***.***>主 题： Re: [leijinjun/sms-bomb] Could not create connection to database server (Issue #4) 数据库配置肯定要改啊，要用你自己的啊发自我的手机-------- 原始邮件 --------发件人： 大魔王啊 @.>日期： 2023年9月6日周三 10:07收件人： leijinjun/sms-bomb @.>抄送： 冰与火丶挣扎 @.>, Comment @.>主 题： Re: [leijinjun/sms-bomb] Could not create connection to database server (Issue #4) 代码都是你的 没有改 还是你的配置 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.***> 不需要建表吗 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

短信api资源要怎么搞啊?
![image](https://github.com/leijinjun/sms-bomb/assets/48475006/d3858cae-b4d3-44bc-9138-113c6a03604b)

**Comment by HHCOMEBACK** [comment]
2023.12.14 最新可用

修复了多处bug，内置1000个api

https://github.com/DianHuaHongZha/callphoneboom

**Comment by leijinjun** [comment]
close
